### ISSUE TITLE
Can't install with pnpm

### ISSUE THREAD

**Issue by Djaler** [toplenboren/simple-git-hooks#41]
```
node_modules/.pnpm/simple-git-hooks@2.2.0/node_modules/simple-git-hooks: Running postinstall script, failed in 126ms
.../node_modules/simple-git-hooks postinstall$ node ./postinstall.js
│ internal/fs/utils.js:307
│     throw err;
│     ^
│ Error: ENOENT: no such file or directory, stat 'D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\package.json'
│     at Object.statSync (fs.js:1086:3)
│     at _getPackageJson (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\simple-git-hooks.js:140:13)
│     at checkSimpleGitHooksInDependencies (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\simple-git-hooks
│     at postinstall (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\postinstall.js:15:9)
│     at Object.<anonymous> (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.2.0\node_modules\simple-git-hooks\postinstall.js:24:1)
│     at Module._compile (internal/modules/cjs/loader.js:1063:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
│     at Module.load (internal/modules/cjs/loader.js:928:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
│     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
│   errno: -4058,
│   syscall: 'stat',
│   code: 'ENOENT',
│   path: 'D:\\Projects\\vue-promise-dialogs\\node_modules\\.pnpm\\simple-git-hooks@2.2.0\\package.json'
│ }
└─ Failed in 127ms
 ERROR  Command failed with exit code 1.
 ```

pnpm version: 5.18.7

**Comment by Djaler** [comment]
Hello. Have you tried to run it on pnpm? It should work, but it is not.
I didn't understand why.
This is what I get:
```
node_modules/.pnpm/simple-git-hooks@2.3.0/node_modules/simple-git-hooks: Running postinstall script, failed in 109ms
.../node_modules/simple-git-hooks postinstall$ node ./postinstall.js
│ internal/fs/utils.js:307
│     throw err;
│     ^
│ Error: ENOENT: no such file or directory, stat 'D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.3.0\package.json'
│     at Object.statSync (fs.js:1086:3)
│     at _getPackageJson (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks\simple-git-hooks.js:173:13)
│     at checkSimpleGitHooksInDependencies (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks\simple-git-hooks
│     at postinstall (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks\postinstall.js:22:9)
│     at Object.<anonymous> (D:\Projects\vue-promise-dialogs\node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks\postinstall.js:31:1)
│     at Module._compile (internal/modules/cjs/loader.js:1063:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
│     at Module.load (internal/modules/cjs/loader.js:928:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
│     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
│   errno: -4058,
│   syscall: 'stat',
│   code: 'ENOENT',
│   path: 'D:\\Projects\\vue-promise-dialogs\\node_modules\\.pnpm\\simple-git-hooks@2.3.0\\package.json'
│ }
```

But if I run `node postinstall.js` in `node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks` manually, it works good

**Comment by Djaler** [comment]
Oh, I understand it just now.
Looks like cwd when script called by pnpm is `node_modules\.pnpm\simple-git-hooks@2.3.0`, not `node_modules\.pnpm\simple-git-hooks@2.3.0\node_modules\simple-git-hooks`. I'll make a fix ASAP

**Comment by Djaler** [comment]
Here it is https://github.com/toplenboren/simple-git-hooks/pull/47

**Comment by toplenboren** [comment]
Thank you for the quick fix :)

I think if you run `npx simple-git-hooks` it should install everything, since cwd should be project root

**Comment by Djaler** [comment]
Damn. Still not work. And now I see why - `packageVersion` is undefined, so arrays comparison returns false.
Do you have any idea why `const { packageVersion } = require('./package.json');` didn't work?
Or we realy can just simplify check to `projDir.includes('.pnpm')`.

P.S. Sorry for this, I just didn't find a way to properly test it locally (with real install)

**Comment by Djaler** [comment]
I am sooo dumb. 
It just should be `const { version: packageVersion }` instead of `const { packageVersion }`. This is what we have without typescript checks.
So, I can fix the current solution or simplify it. What do you prefer?

**Comment by Djaler** [comment]
https://github.com/toplenboren/simple-git-hooks/pull/48

**Comment by toplenboren** [comment]
:) Thank you for the fix

By the way, you can test package locally unsing npm pack. 

Like, simply run `npm pack` in root of `simple-git-hooks` package, and then you get `.tar` archive

After that you simply specify `simple-git-hooks` in `package.json.devDependencies` like this:

```(json)
devDependencies {
  simple-git-hooks: 'path-to-archive.tar'
}
```

**Comment by Djaler** [comment]
I tried this, but pnpm installs local tar archives in different way

**Comment by Djaler** [comment]
But with current simplified check it works good, I successfully tested it

**Comment by Djaler** [comment]
So, will you release this fix?

**Comment by ymatuhin** [comment]
Same problem here
