### ISSUE TITLE
Can't install with nodeLinker: pnpm

### ISSUE THREAD

**Issue by AlexPoleschuk** [toplenboren/simple-git-hooks#89]
```
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/package.json'
    at Object.statSync (node:fs:1695:3)
    at _getPackageJson (/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/node_modules/simple-git-hooks/simple-git-hooks.js:179:13)
    at checkSimpleGitHooksInDependencies (/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/node_modules/simple-git-hooks/simple-git-hooks.js:102:34)
    at postinstall (/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/node_modules/simple-git-hooks/postinstall.js:18:9)
    at Object.<anonymous> (/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/node_modules/simple-git-hooks/postinstall.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/project/node_modules/.store/simple-git-hooks-npm-2.8.1-284fd0e93b/package.json'
}
```

Node.js v20.2.0
Yarn 3
nodeLinker: pnpm

**Comment by AlexPoleschuk** [comment]
I see this problem is similar to #47 

Fix [#90](https://github.com/toplenboren/simple-git-hooks/pull/90)
